buildscript {
    repositories {
        maven {
            name = "MavenCentral"
            url = "https://repo1.maven.org/maven2/"
        }
        maven {
            name = "GTNH"
            url = "http://nexus.gtnewhorizons.com/repository/public/"
        }
        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.2.11.dirty'
    }
}

apply plugin: 'forge'

version = "1.0"
group = "top.codfish.projecteteam"
archivesBaseName = "ProjectETeam"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "eclipse"
}

dependencies {
    compile files('ProjectE-1.7.10-PE1.10.1.jar')
}

// Compile with UTF-8 encoding
compileJava {
    options.encoding = 'UTF-8'
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
